# Run testcafe tests
# https://testcafe.io/documentation/402817/guides/continuous-integration/github-actions
name: Run testcafe tests

on:
  workflow_call:
    inputs:
      slack_webhook_url:
        required: true
        type: string

jobs:
  testcafe:
    runs-on: ubuntu-latest

    steps:
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"

      - name: Publish notifications to slack channel
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#git-e2e-tests'
          webhook-url: ${{ inputs.slack_webhook_url }}
        if: always()
