name: Texts/Books E2E Tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out branch
        uses: actions/checkout@v3
      - name: Grab Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
      - name: Look inside current dir
        run: ls -lh .
      - name: Grab BR's test files
        run: npm run port-br-files
      - name: Confrim `br-e2e-tests` dir
        run: ls -lh br-e2e-tests/
      - name: 📚 📖 Books tests! 📖 📚
        run: npm run test:br