name: BR E2E Tests

on: workflow_call

jobs:
# "rm -rf br-e2e-tests && mkdir br-e2e-tests && npx copyfiles -V -u 5 node_modules/@internetarchive/bookreader/tests/e2e/** br-e2e-tests && npx copyfiles -V -u 5 node_modules/@internetarchive/bookreader/tests/e2e/**/*.* br-e2e-tests && echo 'BR Files ported: \n' && ls -lh br-e2e-tests",

  copy-br-files:
    runs-on: ubuntu-latest
    name: "Port tests over"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
        run: npm i  --ignores-scripts
      - name: Look inside current dir
        run: ls -lh . && cwd && echo ${{ github.workspace }}
      - name: Make ~/br-e2e-tests
        run: rm -rf br-e2e-tests && mkdir br-e2e-tests
      - run: npx copyfiles -V -u 5 node_modules/@internetarchive/bookreader/tests/e2e/** br-e2e-tests
      - run: npx copyfiles -V -u 5 node_modules/@internetarchive/bookreader/tests/e2e/**/*.* br-e2e-tests
      - run: ls -lh br-e2e-tests && pwd && ls -lh .
      - name: Run BR E2E tests!
        run: npx testcafe chrome:headless, firefox:headless, --color --quarantine br-e2e-tests/ia-production/ia-prod-base.js

      # - name: Load node_modules from cache
      #   uses: actions/cache@v2
      #   with:
      #     # Use node_modules from previous jobs
      #     path: node_modules
      #     key: ${{ runner.os }}-node-16-${{ hashFiles('package.json') }}
      


      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'
      #     cache: 'npm'
      #   run: npx testcafe chrome, firefox, --color --quarantine br-e2e-tests/ia-production/ia-prod-base.js


  # br-tests:
  #   runs-on: ubuntu-latest
  #   name: "E2E Tests => archive.org"
  #   needs: copy-br-files

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: './br-e2e-tests'
  #         key: br-e2e-tests-${{ hashFiles('package.json') }}
  #     - uses: DevExpress/testcafe-action@latest
  #       with:
  #         skip-install: true
  #         args: "chrome, firefox, --color --quarantine ./br-e2e-tests/ia-production/ia-prod-base.js"
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'
      #     cache: 'npm'
      # - run: npm global add testcafe
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'
      #     cache: 'npm'
      # - run: npm run run-br-tests
