name: BR E2E Tests

on: workflow_call

jobs:
  copy-br-files:
    runs-on: ubuntu-latest
    name: "Port BookReader tests over"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Cache BookReader test files
        uses: actions/cache@v2
        id: br-files-cache
        with:
          path: 'br-e2e-tests'
          key: ${{ runner.os }}-node-16-${{ hashFiles('package*.json') }}
      - if: steps.br-files-cache.outputs.cache-hit != 'true'
        run: yarn run port-br-files
  
  br-tests:
    runs-on: ubuntu-latest
    name: "Run BookReader's E2E Tests against archive.org"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn testcafe chrome, firefox, --color --quarantine br-e2e-tests/ia-production/ia-prod-base.js
