name: BR E2E Tests

on: workflow_call

jobs:
  copy-br-files:
    runs-on: ubuntu-latest
    name: "run on archive.org"

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Grab Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm i --ignore-scripts
      - name: Look inside current dir
        run: ls -lh .
      - name: Grab BR's test files
        run: npm run port-br-files
      - name: 📚 📖 BR E2E tests! 📖 📚
        run: npm run test:br:headless