name: Texts/Books E2E Tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out branch
        uses: actions/checkout@v3
      - name: Grab Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
      - name: Look inside current dir
        run: ls -lh .
      - name: Grab BR's test files
        run: npm run port-br-files
      - name: 📚 📖 Books tests! 📖 📚
        uses: DevExpress/testcafe-action@latest
        with:
          args: "--color -q -c 2 chrome:headless,firefox:headless test/books"
