name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: c-hive/gha-yarn-cache@v2
      - name: Install node_modules
        run: yarn install

  test:
    - name: Run tests
    - needs: install

    steps:
      - uses: c-hive/gha-yarn-cache@v2
        run: yarn run test
