name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache yarn
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install node_modules
        run: yarn install

  test:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test

    steps:
    # - uses: c-hive/gha-yarn-cache@v2
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome test"
