name: Cron

on:
  schedule:
    # should run every 3hrs on weekdays
    - cron: "0 */3 * * 1-5"
    # for testing purposes (this will run every 5mins everyday)
    # - cron: "*/5 * * * *" 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # run slack-notifier workflow
      - uses: ./.github/actions/run-slack-notifier.yml
        with:
          message: Starting push to main branch e2e tests run...
        secrets:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: check out branch
        uses: actions/checkout@v3

      - name: Grab Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Npm ci
        run: npm ci

      # run testcafe workflow
      - uses: ./.github/actions/run-testcafe.yml
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

