name: Cron tests

on: 
  schedule:
      - cron: "*/15 * * * *" #every 15 mins
      # - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)

jobs:
  install:
    uses: ./.github/workflows/install.yml

  run-e2e-tests:
    needs: install
    uses: ./.github/workflows/run-e2e-tests.yml
