name: Cron

on:
  schedule:
    # changing this for now for testing
    # - cron: "0/3 * * * *"
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out branch
        uses: actions/checkout@v3
      - name: Grab Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Npm ci
        run: npm ci

      # Run testcafe tests
      # https://testcafe.io/documentation/402817/guides/continuous-integration/github-actions
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"

