name: Push to `main`

on:
  push:
    branches: [ main ]

jobs:
  lint-n-circular:
    uses: ./.github/workflows/check-lint-circ.yml

  audio:
    uses: ./.github/workflows/audio.yml

  books:
    uses: ./.github/workflows/books.yml

