name: PRs & Pushes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 27 * * *"

jobs:
  lint-n-circular:
    uses: ./.github/workflows/check-lint-circ.yml

  music:
    uses: ./.github/workflows/music.yml

  books:
    uses: ./.github/workflows/books.yml

  bookreader:
    uses: ./.github/workflows/bookreader-e2e-tests.yml
