name: Run all

on:
  pull_request:
    branches: [ main ]

jobs:
  bookreader:
    uses: ./.github/workflows/bookreader-e2e-tests.yml

  music:
    uses: ./.github/workflows/music.yml

  # books:
  #   uses: ./.github/workflows/books.yml

  # all-tests:
  #   needs: install
  #   uses: ./.github/workflows/run-e2e-tests.yml
