name: Push to `main`

on:
  push:
    branches: [ main ]

jobs:
  notify:
    # run slack-notifier workflow
    uses: ./.github/workflows/run-slack-notifier.yml
    with:
      message: Starting push to main branch e2e tests run...
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  lint-n-circular:
    uses: ./.github/workflows/check-lint-circ.yml

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Grab Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Npm ci
        run: npm ci

      - name: Run TestCafe workflow
        run: npm run test:all

      - name: Publish notifications to slack channel
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#git-e2e-tests'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
