name: Merges to main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  lint-n-circular:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/check-lint-circ.yml

  music:
    if: github.event.pull_request.merged == true  
    uses: ./.github/workflows/audio.yml

  books:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/books.yml

  search:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/search.yml
