name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/install.yml

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: "chrome test"
