name: Pull Request

on:
  pull_request:

jobs:
  lint-n-circular:
    uses: ./.github/workflows/check-lint-circ.yml

  audio:
    uses: ./.github/workflows/audio.yml

  books:
    uses: ./.github/workflows/books.yml

  search:
    uses: ./.github/workflows/search.yml
