# Add GH action workflow for Slack integration for workflows, jobs and steps
# https://github.com/act10ns/slack
name: Slack GH action notifier

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      webhook_url:
        required: true
        type: string

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#git-e2e-tests'
          message: ${{ inputs.message }}
          webhook-url: ${{ inputs.webhook_url }}
        if: always()
